apiVersion: v1
kind: Pod
metadata:
  name: project
  labels:
    app: project
spec:
  containers:
    - name: likith
      image: likithreddysiddala/project:v1
      ports:
        - containerPort: 8080
